[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'forge-std/=lib/forge-std/src/',
    'solady/=lib/solady/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
