[profile.default]
src = "src"
out = "out"
libs = ['dependencies']
solc = '0.8.28'
bytecode_hash = "none"
optimizer_runs = 9999999
via_ir = true

[dependencies]
"@openzeppelin-contracts" = "5.1.0"
"@openzeppelin-contracts-upgradeable" = "5.1.0"
forge-std = "1.9.4"
solady = "0.0.275"
create2-helpers = "0.3.2"
"@uniswap-v3-core" = "1.0.2-solc-0.8-simulate"


[rpc_endpoints]
base = "${BASE_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
optimism_sepolia = "${OP_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASE_ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${BASE_ETHERSCAN_API_KEY}" }
optimism_sepolia = { key = "${OP_SEPOLIA_ETHERSCAN_API_KEY}" }

[fmt]
line_length = 100

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
