[profile.default]
src = "src"
out = "out"
libs = ['dependencies']
solc = '0.8.28'
bytecode_hash = "none"
optimizer_runs = 9999999
via_ir = true


[dependencies]
"@openzeppelin-contracts" = "5.1.0"
"@openzeppelin-contracts-upgradeable" = "5.1.0"
forge-std = "1.9.4"
"@uniswap-v3-periphery" = "1.4.4"
solady = "0.0.275"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
